### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by scoutman57**
Fix "calendar" spelling

---
This change is [Reviewable](https://reviewable.io/reviews/andegna/calender/36)

### CODE REVIEW

**Comment by SamAsEnd** [comment]
I wanna merge this but, not gonna rename the repo name! So I don't wanna break the links

Please change back the links and the composer install part!

**Comment by scoutman57** [comment]
reverted some links back to prevent renaming repo

**Comment by SamAsEnd** [comment]
already applied it #37

**Comment by SamAsEnd** [comment]
@scoutman57 Thanks for your contribution :+1:

**Pull request closed without merging**
